add systemPrompt in Model Settings
withcatai/catai pull request #64
Opened 2024-01-03 20:28 UTC by scenaristeur

fix #63

2024-01-05 10:53 UTC, scenaristeur commented
As you can see in the picture of the chat, 
there is a suprising behaviour  ,after the line "I be a pirate..."
the model add a ": what are you doing ?" but i think it is due to the model i have used doplphin that must not adopt the same chatwrapper ? or is it something else ?

2024-01-05 11:32 UTC, ido-pluto commented
It is also not the model falt only, in the next beta of `@catai/node-llama-cpp` there will be some optimization to the model wrapper, in a way that models will better understand the syntax of the wrapper by using specific Unicode reserved for this purpose. 

You can try using a model with more parameters and it may better understand the model wrapper.

2024-01-09 21:08 UTC, ido-pluto commented
Please change your pull request according to my comments, and I will merge it right away :)

2024-01-12 16:36 UTC, scenaristeur commented
which comments ? what should i change ?

2024-01-13 13:15 UTC, ido-pluto requested changes

2024-01-13 13:15 UTC, ido-pluto commented on server/src/manage-models/bind-class/binds/node-llama-cpp/node-llama-cpp-v2/node-llama-cpp-chat.ts
> +        console.log("models settings", _parent.modelSettings.settings)
It may be a good idea to print the settings but it would be better if it will be printed only once on the `initialize` process on this file:
`server/src/manage-models/bind-class/binds/node-llama-cpp/node-llama-cpp-v2/node-llama-cpp-v2.ts`

2024-01-16 09:59 UTC, vcoolish approved these changes

2024-01-17 14:50 UTC, ido-pluto commented
@scenaristeur sorry for the delay, I noticed I did not publish the review

2024-01-18 09:09 UTC, scenaristeur commented on server/src/manage-models/bind-class/binds/node-llama-cpp/node-llama-cpp-v2/node-llama-cpp-chat.ts
> +        console.log("models settings", _parent.modelSettings.settings)
log the settings when you want,  i just wanted to add a systemPrompt, but sure it should be better in initialize process ;-)

2024-01-18 09:36 UTC, merged